theme: jekyll-theme-minimal
title: ACSIA on GitHub
description: The American Center for Strategic and International Affairs (ACSIA) is a registered nonprofit in the State of New York, dedicated to promoting education for the public good. Learn more at [joinacsia.org](https://www.joinacsia.org) 
